name: Design Systems Examples Publish
on:
  push:
    branches:
      - "main"    
  schedule:
    - cron: '0 20 * * *'

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    
    steps:
    # step 1 use node
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    # step 2 build
    - name: Build
      id: build
      run: |
        yarn    
        npx lerna run build
      continue-on-error: true
      
    # step 3 publish
    - name: Publish
      id: publish
      if: steps.build.outcome == 'success'
      run: |
        curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_1SMQtFZyCW68J9WaxFaHmV5c2cv0/rcCeSGIryP
      continue-on-error: true
      
    # step 4 (optional upon errors) report on Slack
    - name: Slack notification upon failure
      if: steps.build.outcome != 'success'
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_COLOR: '#FF0000'
        SLACK_ICON: https://github.com/rtCamp.png?size=48
        SLACK_MESSAGE: 'Build Failed :no_entry_sign:'
        SLACK_TITLE: Build Failed
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

    # step 5 (optional upon errors) exit with error code
    - name: Failure status
      if: steps.build.outcome != 'success'
      run: exit 1

        
        
        
